---
abstract: 'Render parts of your mail with Text::MicroMason'
author:
  - 'Mark Grimes, E<lt>mgrimes@cpan.orgE<gt>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-MIME-Kit-Renderer-MicroMason
provides:
  Email::MIME::Kit::Renderer::MicroMason:
    file: lib/Email/MIME/Kit/Renderer/MicroMason.pm
    version: 1.21
  Text::MicroMason::MKit:
    file: lib/Email/MIME/Kit/Renderer/MicroMason.pm
    version: 0
requires:
  Carp: 0
  Email::MIME::Kit: 2
  Text::MicroMason: 2
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Email-Mime-Kit-Renderer-MicroMason
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mvgrimes/email-mime-kit-renderer-micromason/tree/master
version: 1.21
